### ISSUE TITLE
Boss rule seemingly ignored

### ISSUE THREAD

**Issue by GunnyWaffle** [quat1024/apathy#1]
Using: `apathy-1.18-1.0.2`
No matter how I configure things, bosses always attack a player. Even when explicitly setting the boss rule to `deny` with an otherwise default mobs.cfg.
I was able to confirm that a boss rule of `pass` is ignored as well. As mobs were ignoring me in the no-mobs playerSet but a wither continued to attack me.

**Comment by quat1024** [comment]
Well that's a bummer, I definitely remember testing some of the Wither
stuff and it worked on my machine™️. Lemme see

**Comment by GunnyWaffle** [comment]
I'm unable to test with `runRuleOptimizer: false` due to it crashing my server: (forgot to say this in my original comment oops)
```
[19:09:44] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'apathy'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.11.jar:?]
        at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.11.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.11.jar:?]
Caused by: java.lang.RuntimeException: Problem initializing config file.
        at agency.highlysuspect.apathy.Init.lambda$onInitialize$0(Init.java:73) ~[apathy-1.18-1.0.2.jar:?]
        at agency.highlysuspect.apathy.Init.installReloadAndRunNow(Init.java:115) ~[apathy-1.18-1.0.2.jar:?]
        at agency.highlysuspect.apathy.Init.onInitialize(Init.java:59) ~[apathy-1.18-1.0.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.11.jar:?]
        ... 15 more
Caused by: java.lang.IllegalArgumentException: Empty collection
        at agency.highlysuspect.apathy.rule.spec.predicate.PredicateSpec.sizeSpecializeNotEmpty(PredicateSpec.java:19) ~[apathy-1.18-1.0.2.jar:?]
        at agency.highlysuspect.apathy.rule.spec.predicate.DifficultyIsPredicateSpec.build(DifficultyIsPredicateSpec.java:25) ~[apathy-1.18-1.0.2.jar:?]
        at agency.highlysuspect.apathy.rule.spec.PredicatedRuleSpec.build(PredicatedRuleSpec.java:60) ~[apathy-1.18-1.0.2.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at agency.highlysuspect.apathy.rule.spec.ChainRuleSpec.build(ChainRuleSpec.java:44) ~[apathy-1.18-1.0.2.jar:?]
        at agency.highlysuspect.apathy.config.MobConfig.finish(MobConfig.java:283) ~[apathy-1.18-1.0.2.jar:?]
        at agency.highlysuspect.apathy.config.Config.read(Config.java:28) ~[apathy-1.18-1.0.2.jar:?]
        at agency.highlysuspect.apathy.Init.lambda$onInitialize$0(Init.java:66) ~[apathy-1.18-1.0.2.jar:?]
        at agency.highlysuspect.apathy.Init.installReloadAndRunNow(Init.java:115) ~[apathy-1.18-1.0.2.jar:?]
        at agency.highlysuspect.apathy.Init.onInitialize(Init.java:59) ~[apathy-1.18-1.0.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.11.jar:?]
        ... 15 more
```

**Comment by quat1024** [comment]
Really sorry about this (and for the delay on solving this)

~~Can you pastebin your `config/apathy/mobs.cfg` and `boss.cfg`? (and `mobs.json` if you're using that)~~ Sorry, I missed that sentence that you were using otherwise default config file.

**Comment by quat1024** [comment]
I was able to reproduce the `runRuleOptimizer: false` crash btw, looks like that mode of operation is just plain busted, and always has been.

**Comment by quat1024** [comment]
Okay, I identified the problem. The Wither choosing entities to fire black Wither skulls at is totally separate from what the Wither itself chooses to "target". If you set `boss: deny`, the Wither can't target players so it won't attempt to actively chase them, but it can still fire black skulls at people standing nearby. Should be an easy fix

**Comment by GunnyWaffle** [comment]
I decided to test the dragon as well just in case and she attacks me. That wither find does make sense though, same for blue skulls I assume?
Same repro. Default config files, set `boss` to `deny` in `mobs.cfg`

**Comment by quat1024** [comment]
Ahhh, testing the enderdragon fight is annoying for me because it's like half the reason i made this mod x)

looks like the enderdragon uses yet *another* method of targeting players apart from the main one this mod hooks, lol

**Comment by quat1024** [comment]
If you want to take this for a spin: https://github.com/quat1024/apathy/actions/runs/1576584214 (click "artifacts", extract the .zip, use the one with the shortest filename) and see if things work ok. I think it works for me but this mod is so dang confusing to test lol.

Gonna try and backport this btw, it's an important fix.

**Comment by GunnyWaffle** [comment]
I tested about everything I could. This seems to be in working order!

Thank you so much for providing support here, let alone keeping this mod alive. This mod allows my friend to play with us, whom otherwise has anxiety and fears with combat and mobs attacking them.

I know you joke a lot about this being over-engineered and over-configurable, but that alone allowed us to fine tune their experience with us while keeping the game fair.

Thanks again! ^^
